### ISSUE TITLE
Question: Recording 48 kHz

### ISSUE THREAD

**Issue by schmurian** [Infineon/GetStarted_IM69D130_With_RaspberryPi#2]
Hi,
I connected the s2go MEMS to a Raspberry Pi and overall I‘m impressed by the quality so far. Great product!
However, when recording with a sample rate of 48 kHz and a bitrate of 16 bits, Frequencies above 12 kHz are just mirrored and the second channel has some short noisy interrupts, which I assume is caused by a misinterpretation of the received signal. I‘ve seen the same behavior with other MEMS microphones so could you tell me if this is inherent to the MEMS type microphones or is this related to the i2s software currently available for these microphones?

The only way I was able to record "real" 48 kHz with no issues on the second channel was with 32 bits.

Thank you!

**Comment by pandayswarnam** [comment]
Hi @schmurian ,

The issue is of dynamic range.

The Shield2Go uses a converter such as the [ADAU7002](https://www.analog.com/media/en/technical-documentation/data-sheets/ADAU7002.pdf) from Analog Devices to convert microphone PDM output into PCM.

PDM is a very simple interface, which just generates a 1 if the current sample has higher amplitude than the previous sample, and a 0 if the current sample is lower than the previous sample. This information must be collected and decimated in the received to generate the PCM information.

Rather than working out how many effective bits of audio you can get from the microphone, you should work the PCM bit depth needed to encode the full microphone dynamic range:
1.      The dynamic range of the IM69D130 is 105dB with a 3MHz clock.
2.      To work out the dynamic range of the PCM word is quite simple. In general you can correlate 1 bit = 6dB, so a 16 bit word can encode 96dB of dynamic range.
3.      Clearly 16 bits is not sufficient for the microphone dynamic range. Even with 768kHz, the IM69D130 microphone dynamic range is reduced by 5dB to 100dB, but still is too much for 16 bit encoding.
4.      You can work this backwards also… To ensure you receive the full microphone dynamic range, you require a processing chain with minimum 105dB/6 = 18 bits word length. This is fairly uncommon so 20b or 24b can be used.

If the only option is to use a 16b word length, the best option is to instead use the [IM69D120](https://www.infineon.com/dgdl/Infineon-IM69D120-DS-v01_00-EN.pdf?fileId=5546d462602a9dc801607a0e41a01a2b), which has a reduce dynamic range of 95dB. This was created for exactly this use case of customers who only have the option of a 16b processing chain. But unfortunately, we do not have the SHiel2Go with IM69D120 microphone. This will require the replacement of the microphone on the Shield2Go. Just removing the IM69D130 and soldering  the IM69D120.

The effect of using a bit depth which less than required is that the microphone SNR will not be evident in the output signal.
As the microphone dynamic range is greater than the word dynamic range, and the digital numbers are all aligned to full scale (0dBFS), which corresponds to the microphone’s largest output signal, the digital encoding will not be able to encode the smallest output signals, which correspond to the mic noise floor.

I hope this explanation helps. Recommendation will be for the user to use minimum of 20 bit encoding system. You could also share the application note to the user [Link](https://www.infineon.com/dgdl/Infineon-AN556%20Digital%20encoding%20requirements%20for%20high%20dynamic%20range%20microphones-AN-v01_00-EN.pdf?fileId=5546d4626102d35a01612d1e33876ad8)

**Comment by pandayswarnam** [comment]
Hi  @schmurian ,
I hope this will clear up your doubts and in case still, you have any thing left open feel free to comment.

thanks
Swarnam
